package environment

import (
	"fmt"
	"strings"
)

// ParticipantHOCON renders one `canton.participants.<name>` block reusing the
// upstream `_participant` anchor — the exact pattern the bundled role config
// uses (conf/canton/app-provider/app.conf), generalized to an arbitrary name
// and a deterministic port block instead of the role port-prefix convention.
func ParticipantHOCON(p Participant) string {
	return fmt.Sprintf(`canton.participants.%[1]s = ${_participant} {
  storage.config.properties.databaseName = %[2]s
  ledger-api.port      = %[3]d
  admin-api.port       = %[4]d
  http-ledger-api.port = %[5]d
  monitoring {
    http-health-server.port = %[6]d
    grpc-health-server.port = %[7]d
  }
}
`, p.Name, p.Database(),
		p.LedgerAPIPort(), p.AdminAPIPort(), p.JSONAPIPort(),
		p.HTTPHealthPort(), p.GRPCHealthPort())
}

// CantonInclude is the HOCON appended to the mounted conf/canton/app.conf. It
// is placed after the base file so the `_participant` anchor it defined is in
// scope. Upstream's own role includes can be kept alongside or dropped; the
// generated participants are additive.
func (t Topology) CantonInclude() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# ---- generated by devkit env (%s) ----\n", t.Name)
	for _, p := range t.Participants {
		b.WriteByte('\n')
		b.WriteString(ParticipantHOCON(p))
	}
	return b.String()
}

// dbEnvKey maps a database name to its CREATE_DATABASE_<name> env key. The
// postgres entrypoint provisions a database per such variable (plan §8).
func dbEnvKey(database string) string {
	return "CREATE_DATABASE_" + strings.ReplaceAll(database, "-", "_")
}

// ComposeOverride renders the compose.override.yaml layered over the pinned
// upstream compose.yaml (used unmodified via -f). It publishes each
// participant's API ports and provisions its database, so the upstream tree is
// never patched (plan §19).
func (t Topology) ComposeOverride() string {
	var ports, dbs strings.Builder
	for _, p := range t.Participants {
		// Publish ledger/admin/JSON plus the gRPC health port — the canton
		// image ships grpc-health-probe, so exposing it lets a boot check
		// probe each generated participant directly.
		for _, port := range []int{p.LedgerAPIPort(), p.AdminAPIPort(), p.JSONAPIPort(), p.GRPCHealthPort()} {
			fmt.Fprintf(&ports, "      - \"%d:%d\"\n", port, port)
		}
		fmt.Fprintf(&dbs, "      %s: \"%s\"\n", dbEnvKey(p.Database()), p.Database())
	}
	return fmt.Sprintf(`# Generated by DevKit env (%s). Layered over the pinned upstream
# compose.yaml (referenced unmodified via -f); the upstream cache is never
# patched. See docs/design/env-topology-spike.md.
services:
  canton:
    ports:
%s  postgres:
    environment:
%s`, t.Name, ports.String(), dbs.String())
}
