package docker

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os/exec"
	"strings"
	"time"
)

const (
	// Splice LocalNet's onboarding flow (DAML package vetting, SV
	// keygen, validator registration) routinely takes 3–5 minutes on a
	// cold start. Splice 0.6.4 cold-start with no cached images was
	// observed taking 18+ minutes on a resource-constrained machine
	// (Splice container stuck in `health: starting` while canton +
	// participants reached healthy), so 25 minutes gives realistic
	// headroom without leaking goroutines indefinitely on a genuinely
	// stuck daemon. The caller can still ^C earlier.
	readinessTimeout  = 25 * time.Minute
	readinessPollWait = 3 * time.Second
)

type ComposeRunner struct {
	ProjectName string
	// ComposeFiles is the ordered list of `-f` files passed to docker
	// compose. Later files override earlier ones.
	ComposeFiles []string
	// EnvFiles is the ordered list of --env-file paths. Compose
	// interpolates variables across these files (and the shell env), but
	// values are loaded literally — for cross-file `${VAR:-default}`
	// expansion the shell env must be primed before docker compose runs.
	EnvFiles []string
	// Env, when non-nil, replaces the inherited process environment for
	// every `docker compose` invocation. WorkDir is the cwd for every
	// invocation. Both must be set whenever ComposeFiles/EnvFiles use
	// relative paths, which they always do for the cached Splice project.
	Env       []string
	WorkDir   string
	LogWriter io.Writer

	// commandFn is the seam tests use to inject a fake docker. Production
	// callers leave it nil; tests set it to capture (and optionally script
	// the output of) every `docker compose ...` invocation. Centralising
	// the construction in command() also guarantees that Dir/Env/Stdout/
	// Stderr are applied uniformly across Up/Down/ps/port — past regressions
	// had individual methods forgetting one or the other.
	commandFn func(ctx context.Context, name string, arg ...string) *exec.Cmd
}

// command constructs the *exec.Cmd for one `docker ...` invocation with
// Dir + Env applied. Every method in this file routes through here so
// no call site can accidentally drop WorkDir or Env again (the bug that
// originally affected Down() and Endpoints()).
func (c *ComposeRunner) command(ctx context.Context, args ...string) *exec.Cmd {
	var cmd *exec.Cmd
	if c.commandFn != nil {
		cmd = c.commandFn(ctx, "docker", args...)
	} else {
		cmd = exec.CommandContext(ctx, "docker", args...)
	}
	cmd.Dir = c.WorkDir
	if c.Env != nil {
		cmd.Env = c.Env
	}
	return cmd
}

// composeBase returns the leading docker-compose argv shared by Up/Down/
// ps/etc.
func (c *ComposeRunner) composeBase() []string {
	args := []string{"compose", "-p", c.ProjectName}
	for _, f := range c.ComposeFiles {
		args = append(args, "-f", f)
	}
	for _, ef := range c.EnvFiles {
		args = append(args, "--env-file", ef)
	}
	return args
}

func (c *ComposeRunner) Up(ctx context.Context) error {
	// We omit --wait deliberately: compose's --wait surfaces transient
	// "unhealthy" states as fatal during long Splice onboarding.
	// WaitForHealthy below does its own polling with a Splice-sized
	// timeout.
	//
	// Compose still respects `depends_on: { condition: service_healthy }`
	// during `up -d` regardless of --wait — and Splice's nginx
	// originally depended on splice with that condition, which timed
	// out the dependency wait (splice onboarding > healthcheck retry
	// budget). That's now handled by the container-rename overlay
	// generated by internal/localnet.WriteContainerRenameOverlay,
	// which downgrades the nginx→splice condition to service_started.
	args := append(c.composeBase(), "up", "-d")

	cmd := c.command(ctx, args...)
	cmd.Stdout = c.LogWriter
	cmd.Stderr = c.LogWriter

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("docker compose up failed: %w", err)
	}
	return nil
}

func (c *ComposeRunner) WaitForHealthy(ctx context.Context) error {
	ctx, cancel := context.WithTimeout(ctx, readinessTimeout)
	defer cancel()

	// Track the last raw `ps` snapshot so the timeout error can report
	// which services were stuck and in what state — without this, the
	// only signal on timeout is "timed out", which forces the user to
	// re-run `docker compose ps` manually to diagnose. The most common
	// stuck-state is splice in `restarting/starting` due to OOM-kill
	// from insufficient Docker memory (see docs/limitations.md).
	var lastSnapshot []byte
	for {
		select {
		case <-ctx.Done():
			return fmt.Errorf("timed out waiting for services to become healthy.\nLast `docker compose ps` snapshot:\n%s", formatHealthSnapshot(lastSnapshot))
		default:
		}

		raw, ready, fatal := c.healthSnapshotRaw(ctx)
		if raw != nil {
			lastSnapshot = raw
		}
		if fatal != nil {
			return fatal
		}
		if ready {
			return nil
		}

		select {
		case <-ctx.Done():
			return fmt.Errorf("timed out waiting for services to become healthy.\nLast `docker compose ps` snapshot:\n%s", formatHealthSnapshot(lastSnapshot))
		case <-time.After(readinessPollWait):
		}
	}
}

// formatHealthSnapshot turns the raw tab-separated `docker compose ps`
// output into a tidy table for the timeout error message.
func formatHealthSnapshot(raw []byte) string {
	if len(raw) == 0 {
		return "  (no services reported)"
	}
	var b strings.Builder
	b.WriteString("  NAME                              STATE        HEALTH\n")
	scanner := bufio.NewScanner(strings.NewReader(string(raw)))
	for scanner.Scan() {
		line := strings.TrimRight(scanner.Text(), "\r")
		if line == "" {
			continue
		}
		parts := strings.Split(line, "\t")
		if len(parts) != 3 {
			continue
		}
		fmt.Fprintf(&b, "  %-32s  %-11s  %s\n",
			parts[0], parts[1], strings.TrimSpace(parts[2]))
	}
	return b.String()
}

// healthSnapshot runs `docker compose ps` once and classifies the result.
// ready=true means every service is in a terminal-good state and the
// poller can stop; fatal!=nil means something is irrecoverably broken
// (e.g. a service exited non-zero) and the caller should fail fast
// instead of polling further.
//
// Empty output (no services at all) is treated as not-ready rather than
// fatal: compose may not have registered the project yet right after
// `up` returns.
func (c *ComposeRunner) healthSnapshot(ctx context.Context) (ready bool, fatal error) {
	_, ready, fatal = c.healthSnapshotRaw(ctx)
	return ready, fatal
}

// healthSnapshotRaw is the variant the WaitForHealthy loop uses so it
// can stash the raw ps output for inclusion in a timeout error.
func (c *ComposeRunner) healthSnapshotRaw(ctx context.Context) (raw []byte, ready bool, fatal error) {
	// Tab-separated to keep parsing trivial even with whitespace in
	// future fields. Order: name, state, health.
	args := append(c.composeBase(), "ps", "--all", "--format", "{{.Name}}\t{{.State}}\t{{.Health}}")
	out, err := c.command(ctx, args...).Output()
	if err != nil {
		// Transient errors (e.g. daemon momentarily unavailable) shouldn't
		// abort the whole wait — keep polling.
		return nil, false, nil
	}
	ready, fatal = classifyHealth(out)
	return out, ready, fatal
}

// classifyHealth is the pure parser behind healthSnapshot. Extracted so
// the readiness logic can be exercised by unit tests against canned
// `docker compose ps` output without invoking docker.
//
// Decision table (per service):
//
//	state=running, health=healthy       → counts toward ready
//	state=running, health=starting      → not ready, keep polling
//	state=running, health=unhealthy     → not ready, keep polling
//	state=running, health=""            → counts toward ready (no healthcheck)
//	state=exited|dead|removing|paused   → fatal (service died)
//	state="" (no services yet)          → not ready, keep polling
//
// The function returns ready=true iff at least one service was reported
// AND every reported service is in a counts-toward-ready bucket.
//
// # Why `running/unhealthy` is not fatal
//
// Splice's container healthchecks routinely report `unhealthy` for a
// stretch during onboarding (DAML package vetting, SV keygen, validator
// registration) before settling green. The container is alive, the
// process is running, and `restart: always` brings it back if it does
// crash — so a transient `unhealthy` is not proof of irrecoverable
// failure. The 15-minute WaitForHealthy timeout (with the post-mortem
// `docker compose ps` snapshot in the error message) is the actual
// gate; classifyHealth's job is just "is this snapshot good enough to
// stop polling?", and the honest answer for unhealthy is "no, wait".
//
// `exited`/`dead`/`removing`/`paused` ARE fatal because the container
// is no longer running — no amount of waiting will produce a healthy
// state from there.
func classifyHealth(raw []byte) (ready bool, fatal error) {
	scanner := bufio.NewScanner(strings.NewReader(string(raw)))
	count := 0
	for scanner.Scan() {
		// Trim only \r (Windows line endings) — NOT all whitespace,
		// because the third column is a tab-delimited empty string for
		// services without a healthcheck and TrimSpace would eat the
		// preceding tab, collapsing 3 columns into 2.
		line := strings.TrimRight(scanner.Text(), "\r")
		if line == "" {
			continue
		}
		// Exactly three columns. If a future `docker compose` release
		// adds more, plain Split would smuggle them into parts[2] and
		// silently break the health-string switch; require the exact
		// shape and keep polling on anything weird.
		parts := strings.Split(line, "\t")
		if len(parts) != 3 {
			return false, nil
		}
		name := parts[0]
		state := parts[1]
		health := strings.TrimSpace(parts[2])
		count++

		switch state {
		case "running":
			switch health {
			case "healthy", "":
				// good
			case "starting":
				return false, nil
			case "unhealthy":
				// Not fatal — Splice flips unhealthy briefly during
				// onboarding. WaitForHealthy's 15-min timeout is the
				// real gate. See decision-table commentary above.
				return false, nil
			default:
				return false, nil
			}
		case "exited", "dead", "removing", "paused":
			return false, fmt.Errorf("service %q is in state %q", name, state)
		default:
			// "created", "restarting", "" — not ready yet.
			return false, nil
		}
	}
	return count > 0, nil
}

// Endpoints returns container-name → human-readable publisher string,
// e.g. `nginx → "0.0.0.0:54321->2000/tcp, 0.0.0.0:54322->3000/tcp"`. The
// value is intentionally a display blob — it's the raw {{.Publishers}}
// template output and may contain multiple comma-separated mappings
// when a single service publishes more than one port. Callers that need
// structured port info should use DiscoverPort() instead, which queries
// `docker compose port` for a specific (service, container-port) pair.
//
// Uses tab as the field separator (instead of space) because Publishers
// values themselves contain spaces, which `SplitN(line, " ", 2)` could
// only partially handle. With a tab separator the right-hand side is
// always exactly the Publishers value, regardless of how many ports it
// holds.
func (c *ComposeRunner) Endpoints(ctx context.Context) map[string]string {
	endpoints := make(map[string]string)
	args := append(c.composeBase(), "ps", "--format", "{{.Name}}\t{{.Publishers}}")
	out, err := c.command(ctx, args...).Output()
	if err != nil {
		return endpoints
	}

	scanner := bufio.NewScanner(strings.NewReader(string(out)))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		parts := strings.SplitN(line, "\t", 2)
		if len(parts) != 2 {
			continue
		}
		endpoints[parts[0]] = strings.TrimSpace(parts[1])
	}
	return endpoints
}

// DiscoverPort returns the host port that the given compose service has
// mapped to its container port. Used when running with TEST_PORT=1 (i.e.
// ephemeral allocation) so we can populate state.Ports with the actual
// daemon-assigned ports.
//
// Returns 0 (not an error) if the service exists but doesn't publish
// the requested container port — caller decides whether that's fatal.
func (c *ComposeRunner) DiscoverPort(ctx context.Context, service string, containerPort int) (int, error) {
	args := append(c.composeBase(), "port", service, fmt.Sprintf("%d", containerPort))
	out, err := c.command(ctx, args...).Output()
	if err != nil {
		// "no port published" returns exit 1 with empty output —
		// surface as port=0 rather than an error.
		return 0, nil
	}
	// Output looks like "0.0.0.0:54321\n". Split on ':' and take the last
	// chunk so IPv6 (e.g. "[::]:54321") also parses.
	s := strings.TrimSpace(string(out))
	if s == "" {
		return 0, nil
	}
	if i := strings.LastIndexByte(s, ':'); i >= 0 {
		s = s[i+1:]
	}
	var port int
	if _, err := fmt.Sscanf(s, "%d", &port); err != nil {
		return 0, fmt.Errorf("parse port %q for %s/%d: %w", s, service, containerPort, err)
	}
	return port, nil
}

func (c *ComposeRunner) Down(ctx context.Context) error {
	args := append(c.composeBase(), "down", "--volumes", "--remove-orphans")
	return c.command(ctx, args...).Run()
}
