package localnet

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/bitdynamics-ab/canton-devkit/internal/registry"
	"github.com/bitdynamics-ab/canton-devkit/internal/splice"
)

// OverlayEnvFile is the filename written to each instance's DataDir at
// `up` time. It captures the exact compose interpolation vars the
// adapter produced so downstream commands (down, logs, pause, restart,
// clean) replay them without re-deriving from the adapter.
const OverlayEnvFile = "overlay.env"

// overlayEnvPath returns the absolute path to the instance's persisted
// overlay env file.
func overlayEnvPath(state *registry.State) string {
	return filepath.Join(state.DataDir, OverlayEnvFile)
}

// WriteOverlayEnv writes the adapter's overlay env to the instance's
// DataDir as a docker-compose-compatible env file. Called once during
// `up`, after port allocation and before `docker compose up`.
func WriteOverlayEnv(dataDir string, overlay map[string]string) (string, error) {
	path := filepath.Join(dataDir, OverlayEnvFile)
	if err := os.MkdirAll(dataDir, 0o700); err != nil {
		return "", fmt.Errorf("create data dir %s: %w", dataDir, err)
	}

	// Sort keys for deterministic output.
	keys := make([]string, 0, len(overlay))
	for k := range overlay {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Auto-generated by canton-devkit localnet up. Do not edit.\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s=%s\n", k, overlay[k])
	}

	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return "", fmt.Errorf("write %s: %w", path, err)
	}
	return path, nil
}

// composeEnvFiles returns the full ordered list of --env-file paths for
// a docker compose invocation against the given instance. The overlay
// env file (written at `up` time) comes last so its values win over
// upstream Splice defaults.
func composeEnvFiles(state *registry.State) ([]string, error) {
	overlay := overlayEnvPath(state)
	if !fileExists(overlay) {
		return nil, fmt.Errorf("overlay.env not found at %s — was this instance started with the current version?", overlay)
	}

	v, err := splice.Resolve(state.SpliceVersion)
	if err != nil {
		return nil, fmt.Errorf("resolve version %q: %w", state.SpliceVersion, err)
	}
	adapter, err := adapterFor(v)
	if err != nil {
		return nil, err
	}
	files := append([]string(nil), adapter.EnvFiles()...)
	files = append(files, overlay)
	return files, nil
}

// composeContext returns the env-file list for a docker compose
// invocation against the given instance.
//
// All compose interpolation vars come from env files — no process-env
// injection needed. The returned env is nil, which makes ComposeRunner
// inherit the calling process's environment (PATH, DOCKER_HOST, etc.).
func composeContext(state *registry.State) (env []string, envFiles []string, err error) {
	files, err := composeEnvFiles(state)
	if err != nil {
		return nil, nil, err
	}
	return nil, files, nil
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// composeProfiles returns the `docker compose --profile` set to replay
// for an existing instance on a service-model compose subcommand
// (restart / pause / ps). Every Splice service is profile-gated, so
// omitting these targets zero services.
//
// Prefers the set persisted at `up` time (state.Profiles). For instances
// created before that field existed (state.Profiles == nil) it falls
// back to re-deriving the adapter's base profiles from the recorded
// Splice version — which covers the core sv/app-provider/app-user/
// swagger-ui services. User `--profile` opt-ins (observability,
// tokens-v2) can't be recovered from old state and are best-effort only
// on the fallback path.
func composeProfiles(state *registry.State) []string {
	if len(state.Profiles) > 0 {
		return state.Profiles
	}
	v, err := splice.Resolve(state.SpliceVersion)
	if err != nil {
		return nil
	}
	adapter, err := adapterFor(v)
	if err != nil {
		return nil
	}
	return adapter.Profiles()
}
