package localnet

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/bitdynamics-ab/canton-devkit/internal/registry"
	"github.com/bitdynamics-ab/canton-devkit/internal/splice"
)

// OverlayEnvFile is the filename written to each instance's DataDir at
// `up` time. It captures the exact compose interpolation vars the
// adapter produced so downstream commands (down, logs, pause, restart,
// clean) replay them without re-deriving from the adapter.
const OverlayEnvFile = "overlay.env"

// overlayEnvPath returns the absolute path to the instance's persisted
// overlay env file.
func overlayEnvPath(state *registry.State) string {
	return filepath.Join(state.DataDir, OverlayEnvFile)
}

// WriteOverlayEnv writes the adapter's overlay env to the instance's
// DataDir as a docker-compose-compatible env file. Called once during
// `up`, after port allocation and before `docker compose up`.
func WriteOverlayEnv(dataDir string, overlay map[string]string) (string, error) {
	path := filepath.Join(dataDir, OverlayEnvFile)
	if err := os.MkdirAll(dataDir, 0o700); err != nil {
		return "", fmt.Errorf("create data dir %s: %w", dataDir, err)
	}

	// Sort keys for deterministic output.
	keys := make([]string, 0, len(overlay))
	for k := range overlay {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Auto-generated by canton-devkit localnet up. Do not edit.\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s=%s\n", k, overlay[k])
	}

	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return "", fmt.Errorf("write %s: %w", path, err)
	}
	return path, nil
}

// composeEnvFiles returns the full ordered list of --env-file paths for
// a docker compose invocation against the given instance. The overlay
// env file (written at `up` time) comes last so its values win over
// upstream Splice defaults.
//
// Preferred path: the overlay.env file exists on disk — append it to
// the adapter's base env files.
//
// Fallback (pre-existing instances without overlay.env): re-derive
// from the adapter and inject vars via the process env, matching the
// pre-persistence behaviour.
func composeEnvFiles(state *registry.State) []string {
	overlay := overlayEnvPath(state)

	// Adapter's base env files (relative to ProjectDir).
	v, err := splice.Resolve(state.SpliceVersion)
	if err != nil {
		// Can't resolve version — return overlay only if it exists.
		if fileExists(overlay) {
			return []string{overlay}
		}
		return nil
	}
	adapter, err := adapterFor(v)
	if err != nil {
		if fileExists(overlay) {
			return []string{overlay}
		}
		return nil
	}
	files := append([]string(nil), adapter.EnvFiles()...)
	if fileExists(overlay) {
		files = append(files, overlay)
	}
	return files
}

// composeContext returns the env-file list and process env for a docker
// compose invocation against the given instance.
//
// When overlay.env exists (the normal case after `up`), all compose
// interpolation vars come from env files — no process-env injection
// needed. The returned env is nil, which makes ComposeRunner inherit
// the calling process's environment (PATH, DOCKER_HOST, etc.).
//
// Fallback (pre-existing instances without overlay.env): re-derives
// from the adapter and injects into the process env, matching the
// pre-persistence behaviour.
func composeContext(state *registry.State) (env []string, envFiles []string, err error) {
	overlay := overlayEnvPath(state)
	if fileExists(overlay) {
		return nil, composeEnvFiles(state), nil
	}

	// Fallback: re-derive from adapter (backward compat).
	v, err := splice.Resolve(state.SpliceVersion)
	if err != nil {
		return nil, nil, fmt.Errorf("resolve version %q from state: %w", state.SpliceVersion, err)
	}
	adapter, err := adapterFor(v)
	if err != nil {
		return nil, nil, err
	}
	overlayVars := adapter.OverlayEnv(splice.InstanceParams{
		Name:       state.Name,
		Version:    v,
		ProjectDir: state.ProjectDir,
	})

	env = os.Environ()
	for k, v := range overlayVars {
		env = append(env, k+"="+v)
	}
	return env, adapter.EnvFiles(), nil
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}
