package localnet

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// splice610Containers lists every service that has a hardcoded
// `container_name:` in Splice LocalNet's compose.yaml at the time of
// writing (verified against both 0.5.18 and 0.6.4 — the list is
// identical across both majors).
//
// Adding a new container name when Splice changes upstream is a 1-line
// edit here. We keep the list explicit (rather than parsing compose.yaml
// at runtime) for two reasons:
//   - Determinism: a renamed service is caught by the compile + test
//     pipeline rather than only at runtime.
//   - Simplicity: avoids dragging a YAML parser into the binary for
//     what is fundamentally a known-set problem.
var splice610Containers = []string{
	"ans-web-ui-app-provider",
	"ans-web-ui-app-user",
	"canton",
	"multi-sync-ready",
	"multi-sync-startup",
	"nginx",
	"postgres",
	"scan-web-ui",
	"splice",
	"sv-web-ui",
	"swagger-ui",
	"wallet-web-ui-app-provider",
	"wallet-web-ui-app-user",
	"wallet-web-ui-sv",
}

// WriteContainerRenameOverlay generates a compose overlay file that
// rewrites every `container_name:` from <original> to <prefix><original>.
// Without this overlay, two `localnet up` invocations would collide on
// docker daemon-global container names (e.g. both want to create
// `postgres`).
//
// The overlay file is written to <dataDir>/containers.yaml. Caller
// appends it to the ComposeFiles list when invoking docker compose.
//
// Returns the absolute path of the written file.
func WriteContainerRenameOverlay(dataDir, prefix string) (string, error) {
	if prefix == "" {
		return "", fmt.Errorf("container prefix must be non-empty")
	}
	if err := os.MkdirAll(dataDir, 0o700); err != nil {
		return "", fmt.Errorf("create data dir %s: %w", dataDir, err)
	}

	var b strings.Builder
	b.WriteString("# Generated by canton-devkit. Renames every hardcoded\n")
	b.WriteString("# container_name in the upstream Splice LocalNet compose so\n")
	b.WriteString("# multiple instances can coexist on a single Docker daemon.\n")
	b.WriteString("services:\n")

	// Deterministic order makes the file easy to diff/inspect.
	names := append([]string(nil), splice610Containers...)
	sort.Strings(names)
	for _, svc := range names {
		fmt.Fprintf(&b, "  %s:\n    container_name: %s%s\n", svc, prefix, svc)
	}

	path := filepath.Join(dataDir, "containers.yaml")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", fmt.Errorf("write overlay %s: %w", path, err)
	}
	return path, nil
}
