package localnet

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// splice610Containers lists every service that has a hardcoded
// `container_name:` in Splice LocalNet's compose.yaml at the time of
// writing (verified against both 0.5.18 and 0.6.4 — the list is
// identical across both majors).
//
// Adding a new container name when Splice changes upstream is a 1-line
// edit here. We keep the list explicit (rather than parsing compose.yaml
// at runtime) for two reasons:
//   - Determinism: a renamed service is caught by the compile + test
//     pipeline rather than only at runtime.
//   - Simplicity: avoids dragging a YAML parser into the binary for
//     what is fundamentally a known-set problem.
var splice610Containers = []string{
	"ans-web-ui-app-provider",
	"ans-web-ui-app-user",
	"canton",
	"multi-sync-ready",
	"multi-sync-startup",
	"nginx",
	"postgres",
	"scan-web-ui",
	"splice",
	"sv-web-ui",
	"swagger-ui",
	"wallet-web-ui-app-provider",
	"wallet-web-ui-app-user",
	"wallet-web-ui-sv",
}

// WriteContainerRenameOverlay generates a compose overlay file that
// rewrites every `container_name:` from <original> to <prefix><original>
// AND relaxes the dependency conditions that block bring-up.
//
// Two reasons one overlay covers both:
//
//  1. Container-name rename: without it, two `localnet up` invocations
//     collide on docker daemon-global container names (e.g. both want
//     to create `postgres`).
//  2. depends_on relaxation: Splice's compose.yaml declares
//     `nginx depends_on splice (condition: service_healthy)` — but
//     splice's onboarding (DAML package vetting, SV keygen, validator
//     registration) routinely takes 5-10 min while splice's container
//     healthcheck retry budget is ~5 min. Compose times out the
//     dependency wait on `docker compose up -d` / `start` and reports
//     `dependency failed to start: container ... is unhealthy`, even
//     though the splice container is still alive and would settle.
//     We override JUST that condition to `service_started` so compose
//     stops blocking; ComposeRunner.WaitForHealthy then polls for real
//     readiness with a 15-min, Splice-sized timeout.
//
// The overlay file is written to <dataDir>/containers.yaml. Caller
// appends it to the ComposeFiles list when invoking docker compose.
//
// Returns the absolute path of the written file.
func WriteContainerRenameOverlay(dataDir, prefix string) (string, error) {
	if prefix == "" {
		return "", fmt.Errorf("container prefix must be non-empty")
	}
	if err := os.MkdirAll(dataDir, 0o700); err != nil {
		return "", fmt.Errorf("create data dir %s: %w", dataDir, err)
	}

	var b strings.Builder
	b.WriteString("# Generated by canton-devkit. Two functions:\n")
	b.WriteString("#   1. Renames every hardcoded container_name so multiple\n")
	b.WriteString("#      instances can coexist on a single Docker daemon.\n")
	b.WriteString("#   2. Relaxes nginx's depends_on:splice from\n")
	b.WriteString("#      service_healthy to service_started — splice's\n")
	b.WriteString("#      onboarding outlasts compose's dep-health budget.\n")
	b.WriteString("#      Real readiness is polled by WaitForHealthy.\n")
	b.WriteString("services:\n")

	// Deterministic order makes the file easy to diff/inspect.
	names := append([]string(nil), splice610Containers...)
	sort.Strings(names)
	for _, svc := range names {
		fmt.Fprintf(&b, "  %s:\n    container_name: %s%s\n", svc, prefix, svc)
		if svc == "nginx" {
			// Per-key merge: compose merges depends_on by service name,
			// so this override applies ONLY to the splice entry — the
			// other nginx dependencies (wallet-web-ui-*) keep their
			// upstream-declared conditions.
			b.WriteString("    depends_on:\n")
			b.WriteString("      splice:\n")
			b.WriteString("        condition: service_started\n")
		}
	}

	path := filepath.Join(dataDir, "containers.yaml")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", fmt.Errorf("write overlay %s: %w", path, err)
	}
	return path, nil
}

// SplicePortInternal lists the container ports the splice service
// publishes. Same naming convention as CantonPortInternal — the
// <role>903 pattern is from Splice's compose port block.
//
// These ports use the same `${TEST_PORT-N:}M` pattern as the Canton
// participant ports, so they end up on 0.0.0.0 with Docker-assigned
// ephemeral host ports when TEST_PORT is empty.
var SplicePortInternal = []int{2903, 3903, 4903}

// loopbackPortServices enumerates every Splice compose service that
// publishes host ports, along with the container-side ports and the
// compose env-var pattern for the host side. Services whose host port
// is an env-var (nginx, postgres, swagger-ui) use the "${VAR}" form
// so the overlay reuses the allocated ephemeral value. Services whose
// host port is Docker-assigned (canton, splice) use "0" so Docker
// picks a free port.
//
// The data is intentionally kept as a literal table (not derived from
// adapter.EndpointServices or CantonPortInternal) so that a Splice
// upstream port-list change is caught by the cross-reference test
// rather than silently masked by dynamic derivation.
type loopbackPort struct {
	// HostExpr is "0" for Docker-ephemeral, or "${VAR}" for env-driven.
	HostExpr string
	// ContainerExpr is usually a literal container port. For nginx UI
	// ports it must stay env-driven too: Splice templates nginx's
	// `listen` directives from the same vars DevKit overrides for
	// deterministic host ports.
	ContainerExpr string
}

type loopbackService struct {
	Name  string
	Ports []loopbackPort
}

// loopbackPortTable returns the full list of services whose ports must
// be overridden to bind to 127.0.0.1. Returned as a function (not a
// package-level var) so tests can call it without an init-order issue.
func loopbackPortTable() []loopbackService {
	return []loopbackService{
		{
			Name: "canton",
			Ports: []loopbackPort{
				{"0", "2901"}, {"0", "2902"}, {"0", "2975"},
				{"0", "3901"}, {"0", "3902"}, {"0", "3975"},
				{"0", "4901"}, {"0", "4902"}, {"0", "4975"},
			},
		},
		{
			Name: "splice",
			Ports: []loopbackPort{
				{"0", "2903"}, {"0", "3903"}, {"0", "4903"},
			},
		},
		{
			Name: "nginx",
			Ports: []loopbackPort{
				{"${APP_USER_UI_PORT}", "${APP_USER_UI_PORT}"},
				{"${APP_PROVIDER_UI_PORT}", "${APP_PROVIDER_UI_PORT}"},
				{"${SV_UI_PORT}", "${SV_UI_PORT}"},
			},
		},
		{
			Name: "postgres",
			Ports: []loopbackPort{
				{"${DB_PORT}", "5432"},
			},
		},
		{
			Name: "swagger-ui",
			Ports: []loopbackPort{
				{"${SWAGGER_UI_PORT}", "8080"},
			},
		},
	}
}

// WriteLoopbackPortsOverlay generates a compose overlay that forces
// every published port to bind to 127.0.0.1 (loopback only) instead
// of the upstream default of 0.0.0.0 (all interfaces).
//
// Without this overlay, the canton, splice, postgres, and swagger-ui
// containers are reachable from any host on the local network — a
// security issue for a dev tool that exposes unauthenticated gRPC,
// database, and HTTP endpoints.
//
// The overlay uses the `!override` YAML tag (Docker Compose v2.24.0+,
// Compose Specification §merge) to REPLACE rather than append the
// ports list. Without `!override`, compose's default sequence-merge
// would concatenate the 127.0.0.1-bound entries onto the existing
// 0.0.0.0-bound ones, resulting in dual bindings.
//
// The overlay is written to <dataDir>/loopback-ports.yaml. Caller
// appends it to the ComposeFiles list AFTER the container-rename
// overlay so both take effect.
//
// Returns the absolute path of the written file.
func WriteLoopbackPortsOverlay(dataDir string) (string, error) {
	if err := os.MkdirAll(dataDir, 0o700); err != nil {
		return "", fmt.Errorf("create data dir %s: %w", dataDir, err)
	}

	var b strings.Builder
	b.WriteString("# Generated by canton-devkit.\n")
	b.WriteString("# Forces all published ports to bind to loopback only.\n")
	b.WriteString("# Requires Docker Compose v2.24.0+ for the !override YAML tag.\n")
	b.WriteString("services:\n")

	for _, svc := range loopbackPortTable() {
		fmt.Fprintf(&b, "  %s:\n", svc.Name)
		b.WriteString("    ports: !override\n")
		for _, p := range svc.Ports {
			fmt.Fprintf(&b, "      - \"127.0.0.1:%s:%s\"\n", p.HostExpr, p.ContainerExpr)
		}
	}

	path := filepath.Join(dataDir, "loopback-ports.yaml")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", fmt.Errorf("write overlay %s: %w", path, err)
	}
	return path, nil
}
