package localnet

import (
	"context"
	"errors"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"github.com/bitdynamics-ab/canton-devkit/internal/api/types"
	"github.com/bitdynamics-ab/canton-devkit/internal/docker"
	"github.com/bitdynamics-ab/canton-devkit/internal/registry"
)

func installFakeUIProbe(t *testing.T, fn func(ctx context.Context, rawURL string) error) {
	t.Helper()
	prev := uiProbeFn
	uiProbeFn = fn
	t.Cleanup(func() { uiProbeFn = prev })
}

// recordingUIProbe is a fake probe that records every URL it was asked
// to check and fails those in failURLs. Concurrency-safe: the probe
// runs from multiple goroutines.
type recordingUIProbe struct {
	mu       sync.Mutex
	calls    []string
	failWith map[string]error // URL → error; nil entry = reachable
}

func (p *recordingUIProbe) probe(_ context.Context, rawURL string) error {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.calls = append(p.calls, rawURL)
	return p.failWith[rawURL]
}

func (p *recordingUIProbe) called() []string {
	p.mu.Lock()
	defer p.mu.Unlock()
	return append([]string(nil), p.calls...)
}

func TestDefaultUIProbe_AnyHTTPStatusIsReachable(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusNotFound) // 404 still proves nginx answers
	}))
	defer srv.Close()
	if err := defaultUIProbe(context.Background(), srv.URL); err != nil {
		t.Errorf("404 endpoint should count as reachable, got %v", err)
	}
}

func TestDefaultUIProbe_RedirectIsReachableWithoutFollowing(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/loop" {
			t.Error("probe should not follow redirects")
		}
		http.Redirect(w, r, "/loop", http.StatusFound)
	}))
	defer srv.Close()
	if err := defaultUIProbe(context.Background(), srv.URL); err != nil {
		t.Errorf("30x endpoint should count as reachable, got %v", err)
	}
}

// TestDefaultUIProbe_EmptyReplyIsUnreachable reproduces the stale
// loopback-overlay failure mode: the TCP accept succeeds (docker-proxy
// owns the host port) but the connection closes with zero HTTP bytes.
func TestDefaultUIProbe_EmptyReplyIsUnreachable(t *testing.T) {
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("listen: %v", err)
	}
	defer func() { _ = ln.Close() }()
	go func() {
		for {
			conn, aerr := ln.Accept()
			if aerr != nil {
				return
			}
			_ = conn.Close() // accept, then slam shut: the "empty reply"
		}
	}()

	perr := defaultUIProbe(context.Background(), "http://"+ln.Addr().String())
	if perr == nil {
		t.Fatal("empty-reply endpoint should be unreachable")
	}
	if detail := uiProbeErrorDetail(perr); !strings.Contains(detail, "empty reply") {
		t.Errorf("detail = %q, want the empty-reply explanation", detail)
	}
}

func TestUIProbeErrorDetail_Timeout(t *testing.T) {
	got := uiProbeErrorDetail(context.DeadlineExceeded)
	if !strings.Contains(got, "no HTTP response within") {
		t.Errorf("timeout detail = %q", got)
	}
}

func TestHasStaleLoopbackOverlay(t *testing.T) {
	stale := `# Generated by canton-devkit.
services:
  nginx:
    ports: !override
      - "127.0.0.1:32771:2000"
      - "127.0.0.1:32772:3000"
      - "127.0.0.1:32773:4000"
`
	current := `# Generated by canton-devkit.
services:
  nginx:
    ports: !override
      - "127.0.0.1:${APP_USER_UI_PORT}:${APP_USER_UI_PORT}"
      - "127.0.0.1:${SV_UI_PORT}:${SV_UI_PORT}"
  postgres:
    ports: !override
      - "127.0.0.1:${DB_PORT}:5432"
`
	cases := []struct {
		name    string
		content string // "" = don't write the file
		want    bool
	}{
		{"pre-136 fixed container ports", stale, true},
		{"current env-templated ports", current, false},
		{"missing overlay", "", false},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			dir := t.TempDir()
			if c.content != "" {
				if err := os.WriteFile(filepath.Join(dir, "loopback-ports.yaml"), []byte(c.content), 0o644); err != nil {
					t.Fatalf("write overlay: %v", err)
				}
			}
			if got := hasStaleLoopbackOverlay(dir); got != c.want {
				t.Errorf("hasStaleLoopbackOverlay = %v, want %v", got, c.want)
			}
		})
	}
	if hasStaleLoopbackOverlay("") {
		t.Error("empty dataDir must not count as stale")
	}
}

func TestProbeUIEndpoints_MarksOnlyBrowserUIPorts(t *testing.T) {
	probe := &recordingUIProbe{failWith: map[string]error{
		"http://localhost:4485": io.EOF,
	}}
	installFakeUIProbe(t, probe.probe)

	s := &registry.State{
		Name:    "demo",
		DataDir: t.TempDir(),
		Ports: map[string]int{
			"app_user_ui": 4485,
			"sv_ui":       4487,
			"swagger_ui":  9090, // http, but not overlay-affected: not probed
			"postgres":    5432,
		},
	}
	endpoints := endpointsFromPorts(s.Ports)
	probeUIEndpoints(context.Background(), s, endpoints)

	byPort := map[int]types.Endpoint{}
	for _, e := range endpoints {
		byPort[e.Port] = e
	}
	if got := byPort[4485]; got.Reachability != types.ReachabilityUnreachable ||
		!strings.Contains(got.ReachabilityDetail, "empty reply") {
		t.Errorf("app_user_ui = %+v, want unreachable with empty-reply detail", got)
	}
	if got := byPort[4487]; got.Reachability != types.ReachabilityOK {
		t.Errorf("sv_ui reachability = %q, want %q", got.Reachability, types.ReachabilityOK)
	}
	for _, port := range []int{9090, 5432} {
		if got := byPort[port]; got.Reachability != "" {
			t.Errorf("port %d reachability = %q, want unprobed", port, got.Reachability)
		}
	}
	if calls := probe.called(); len(calls) != 2 {
		t.Errorf("probe called for %v, want exactly the two UI ports", calls)
	}
}

func TestProbeUIEndpoints_StaleOverlayEnrichesDetail(t *testing.T) {
	probe := &recordingUIProbe{failWith: map[string]error{
		"http://localhost:4485": io.EOF,
	}}
	installFakeUIProbe(t, probe.probe)

	dataDir := t.TempDir()
	staleYAML := "services:\n  nginx:\n    ports: !override\n      - \"127.0.0.1:32771:2000\"\n"
	if err := os.WriteFile(filepath.Join(dataDir, "loopback-ports.yaml"), []byte(staleYAML), 0o644); err != nil {
		t.Fatalf("write overlay: %v", err)
	}
	s := &registry.State{Name: "demo", DataDir: dataDir, Ports: map[string]int{"app_user_ui": 4485}}
	endpoints := endpointsFromPorts(s.Ports)
	probeUIEndpoints(context.Background(), s, endpoints)

	if !strings.Contains(endpoints[0].ReachabilityDetail, "stale loopback-ports.yaml") {
		t.Errorf("detail = %q, want stale-overlay mention", endpoints[0].ReachabilityDetail)
	}
}

func seedReachabilityInstance(t *testing.T, name string, status registry.Status, ports map[string]int) *registry.State {
	t.Helper()
	s := registry.NewState(name, "0.6.4")
	s.Status = status
	s.DataDir = t.TempDir()
	s.Ports = ports
	if err := registry.Write(s); err != nil {
		t.Fatalf("seed %q: %v", name, err)
	}
	return s
}

func TestUIReachabilityCheck_SkipsWithoutRunningInstances(t *testing.T) {
	t.Setenv("CANTON_DEVKIT_REGISTRY", t.TempDir())
	seedReachabilityInstance(t, "asleep", registry.StatusStopped, map[string]int{"app_user_ui": 4485})
	probe := &recordingUIProbe{}
	installFakeUIProbe(t, probe.probe)

	got := uiReachabilityCheck(context.Background())
	if got.Status != docker.StatusSkipped {
		t.Errorf("status = %v, want skip", got.Status)
	}
	if calls := probe.called(); len(calls) != 0 {
		t.Errorf("stopped instances must not be probed, got %v", calls)
	}
}

func TestUIReachabilityCheck_AllReachableIsOK(t *testing.T) {
	t.Setenv("CANTON_DEVKIT_REGISTRY", t.TempDir())
	seedReachabilityInstance(t, "demo", registry.StatusRunning,
		map[string]int{"app_user_ui": 4485, "app_provider_ui": 4486, "sv_ui": 4487})
	probe := &recordingUIProbe{}
	installFakeUIProbe(t, probe.probe)

	got := uiReachabilityCheck(context.Background())
	if got.Status != docker.StatusOK {
		t.Errorf("status = %v, want OK; detail=%q", got.Status, got.Detail)
	}
	if calls := probe.called(); len(calls) != 3 {
		t.Errorf("probe calls = %v, want all three UI ports", calls)
	}
}

func TestUIReachabilityCheck_UnreachableWarnsWithRemediation(t *testing.T) {
	t.Setenv("CANTON_DEVKIT_REGISTRY", t.TempDir())
	s := seedReachabilityInstance(t, "old-instance", registry.StatusRunning,
		map[string]int{"app_user_ui": 4485, "sv_ui": 4487})
	staleYAML := "services:\n  nginx:\n    ports: !override\n      - \"127.0.0.1:32771:2000\"\n"
	if err := os.WriteFile(filepath.Join(s.DataDir, "loopback-ports.yaml"), []byte(staleYAML), 0o644); err != nil {
		t.Fatalf("write overlay: %v", err)
	}
	probe := &recordingUIProbe{failWith: map[string]error{
		"http://localhost:4485": io.EOF,
		"http://localhost:4487": io.EOF,
	}}
	installFakeUIProbe(t, probe.probe)

	got := uiReachabilityCheck(context.Background())
	if got.Status != docker.StatusWarn {
		t.Fatalf("status = %v, want warn; detail=%q", got.Status, got.Detail)
	}
	for _, want := range []string{"old-instance/app_user_ui", "empty reply", "stale loopback-ports.yaml"} {
		if !strings.Contains(got.Detail, want) {
			t.Errorf("detail missing %q\ndetail: %s", want, got.Detail)
		}
	}
	for _, want := range []string{"dpm localnet up --name old-instance", "Recreate in the Web UI"} {
		if !strings.Contains(got.Remediation, want) {
			t.Errorf("remediation missing %q\nremediation: %s", want, got.Remediation)
		}
	}
}

func TestUIReachabilityCheck_RegistryUnreadableSkips(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("CANTON_DEVKIT_REGISTRY", dir)
	if err := os.WriteFile(filepath.Join(dir, "index.json"), []byte("{not json"), 0o644); err != nil {
		t.Fatalf("write index: %v", err)
	}
	got := uiReachabilityCheck(context.Background())
	if got.Status != docker.StatusSkipped {
		t.Errorf("status = %v, want skip on unreadable registry", got.Status)
	}
}

// TestCollectDoctor_IncludesUIReachability pins the doctor wiring: the
// probe result lands in the Network section (label contains "ports")
// and a broken instance degrades it to warn without flipping rep.OK.
func TestCollectDoctor_IncludesUIReachability(t *testing.T) {
	t.Setenv("CANTON_DEVKIT_REGISTRY", t.TempDir())
	seedReachabilityInstance(t, "old-instance", registry.StatusRunning, map[string]int{"app_user_ui": 4485})
	probe := &recordingUIProbe{failWith: map[string]error{"http://localhost:4485": io.EOF}}
	installFakeUIProbe(t, probe.probe)

	rep, err := CollectDoctor(context.Background(), DoctorOptions{
		GOOS:       "linux",
		GOARCH:     "amd64",
		ListenFunc: fakeListenOK,
		Prober: func(context.Context, docker.Options) *docker.Report {
			return &docker.Report{Results: []docker.CheckResult{{Name: "Docker CLI", Status: docker.StatusOK}}}
		},
	})
	if err != nil {
		t.Fatalf("CollectDoctor: %v", err)
	}
	var section string
	var check types.PreflightCheck
	for _, sec := range rep.Sections {
		for _, c := range sec.Checks {
			if c.Label == uiReachabilityCheckName {
				section, check = sec.Title, c
			}
		}
	}
	if section != "Network" {
		t.Errorf("check filed under %q, want Network", section)
	}
	if check.Result != "warn" {
		t.Errorf("result = %q, want warn", check.Result)
	}
	if len(check.Remediation) == 0 || !strings.Contains(strings.Join(check.Remediation, "\n"), "old-instance") {
		t.Errorf("remediation should name the instance, got %v", check.Remediation)
	}
	if !rep.OK {
		t.Error("rep.OK = false; UI reachability is advisory and must not fail doctor")
	}
}

func TestUIReachabilityCheck_ErrorDetailFallsBackToRawError(t *testing.T) {
	got := uiProbeErrorDetail(errors.New("connect: connection refused"))
	if got != "connect: connection refused" {
		t.Errorf("fallback detail = %q", got)
	}
}
