# Renders the markdown summary tables (per-release breakdown + all-time
# per-platform totals) embedded in docs/assets/release-downloads.md.
# Invoked as: jq -nr --argjson data "$DATA" -f release-stats-table.jq

def display_name:
  {
    "darwin_arm64": "macOS (arm64)",
    "linux_amd64":  "Linux (amd64)",
    "windows_amd64":"Windows (amd64)",
    "deb":          "Debian (.deb)"
  }[.];

($data) as $d
| ($d.platforms | map(display_name)) as $platCols
| ($d.releases | reverse | map(
    . as $r
    | "| \($r.tag) | \($r.date) | " +
      ($d.platforms | map($r.by_platform[.] | tostring) | join(" | ")) +
      " | \($r.total) |"
  ) | join("\n")) as $releaseRows
| ($d.platforms | map(. as $p | "| " + ($p|display_name) + " | \($d.platform_totals[$p]) |") | join("\n")) as $platformRows
|
"<!-- Generated by scripts/release-stats.sh — do not edit by hand. -->\n" +
"\n**Downloads per release** (newest first)\n\n" +
"| Release | Date | " + ($platCols | join(" | ")) + " | Total |\n" +
"|---|---|" + ($platCols | map("---") | join("|")) + "|---|\n" +
$releaseRows +
"\n\n**All-time downloads per platform**\n\n" +
"| Platform | Downloads |\n" +
"|---|---|\n" +
$platformRows +
"\n"
